const whatToReplace = [
  [/\bdog(s?)\b/gi, "🐶$1"],
  [/\bcat(s?)\b/gi, "🐱$1"],
  [/\bmouse(s?)\b/gi, "🐭$1"],
  [/\bhamster(s?)\b/gi, "🐹$1"],
  [/\brabbit(s?)\b/gi, "🐰$1"],
  [/\bfox(s?)\b/gi, "🦊$1"],
  [/\bbear(s?)\b/gi, "🐻$1"],
  [/\bpanda(s?)\b/gi, "🐼$1"],
  [/\bkoala(s?)\b/gi, "🐨$1"],
  [/\btiger(s?)\b/gi, "🐯$1"],
  [/\blion(s?)\b/gi, "🦁$1"],
  [/\bcow(s?)\b/gi, "🐮$1"],
  [/\bpig(s?)\b/gi, "🐷$1"],
  [/\bfrog(s?)\b/gi, "🐸$1"],
  [/\bmonkey(s?)\b/gi, "🐵$1"],
  [/\bchicken(s?)\b/gi, "🐔$1"],
  [/\bpenguin(s?)\b/gi, "🐧$1"],
  [/\bbird(s?)\b/gi, "🐦$1"],
  [/\bduck(s?)\b/gi, "🦆$1"],
  [/\beagle(s?)\b/gi, "🦅$1"],
  [/\bowl(s?)\b/gi, "🦉$1"],
  [/\bbat(s?)\b/gi, "🦇$1"],
  [/\bwolf(s?)\b/gi, "🐺$1"],
  [/\bboar(s?)\b/gi, "🐗$1"],
  [/\bhorse(s?)\b/gi, "🐴$1"],
  [/\bunicorn(s?)\b/gi, "🦄$1"],
  [/\bbee(s?)\b/gi, "🐝$1"],
  [/\bbug(s?)\b/gi, "🐛$1"],
  [/\bbutterfly(s?)\b/gi, "🦋$1"],
  [/\bsnail(s?)\b/gi, "🐌$1"],
  [/\boctopus(s?)\b/gi, "🐙$1"],
  [/\bfish(es?)\b/gi, "🐟$1"],
  [/\btropical fish(es?)\b/gi, "🐠$1"],
  [/\bblowfish(es?)\b/gi, "🐡$1"],
  [/\bdolphin(s?)\b/gi, "🐬$1"],
  [/\bwhale(s?)\b/gi, "🐳$1"],
  [/\bcrocodile(s?)\b/gi, "🐊$1"],
  [/\bturtle(s?)\b/gi, "🐢$1"],
  [/\bsnake(s?)\b/gi, "🐍$1"],
  [/\blizard(s?)\b/gi, "🦎$1"],
  [/\bscorpion(s?)\b/gi, "🦂$1"],
  [/\bcrab(s?)\b/gi, "🦀$1"],
  [/\bshark(s?)\b/gi, "🦈$1"],
  [/\bdeer(s?)\b/gi, "🦌$1"],
  [/\bgiraffe(s?)\b/gi, "🦒$1"],
  [/\bzebra(s?)\b/gi, "🦓$1"],
  [/\bgorilla(s?)\b/gi, "🦍$1"],
  [/\belephant(s?)\b/gi, "🐘$1"],
  [/\brhinoceros(s?)\b/gi, "🦏$1"],
  [/\bhippopotamus(s?)\b/gi, "🦛$1"],
  [/\bkangaroo(s?)\b/gi, "🦘$1"],
  [/\bbadger(s?)\b/gi, "🦡$1"],
  [/\bswan(s?)\b/gi, "🦢$1"],
  [/\bpeacock(s?)\b/gi, "🦚$1"],
  [/\bparrot(s?)\b/gi, "🦜$1"],
  [/\blobster(s?)\b/gi, "🦞$1"],
  [/\bmosquito(es?)\b/gi, "🦟$1"],
  [/\bmicrobe(s?)\b/gi, "🦠$1"],
];

const walk = document.createTreeWalker(
  document.body,
  NodeFilter.SHOW_TEXT,
  null,
  false
);
let node;
while ((node = walk.nextNode())) {
  for (let [rx, replacement] of whatToReplace) {
    node.nodeValue = node.nodeValue.replace(rx, replacement);
  }
}
